apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: Giuseppe-blog
#data:
#  BLOG_TITLE: "My GitOps Blog"
#  BLOG_SUBTITLE: "Lear more about GitOps and ArgoCD"
#  THEME: "dark"
# Exemple de modification dans k8s/blog/configmap.yaml*
data:
  BLOG_TITLE: "Le Blog de Giuseppe Anelli"
  BLOG_SUBTITLE: "Mes aventures GitOps"
  AUTHOR: "GiuseppeAnelli"
  VERSION: "1.0.0"
